language: c
dist: xenial
git:
  depth: false
  quiet: true

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools
  snaps:
    - name: ubuntu-make
      confinement: classic

install:
  - pip3 install --user adafruit-nrfutil
  - umake electronics arduino $HOME/Arduino
  - export PATH=$HOME/Arduino:$PATH
  - arduino --pref "boardsmanager.additional.urls=https://adafruit.github.io/arduino-board-index/package_adafruit_index.json --save-prefs
  - arduino --install-boards adafruit:nrf52
  - arduino --install-library "Adafruit GFX","Adafruit NeoPixel","Adafruit SSD1306"

before_script:

  
script:
  - arduino --version
   #- build_nrf5x_platforms
