language: c
dist: xenial
git:
  depth: false
  quiet: true

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools
  snap:
    - ubuntu-make

install:
  - pip3 install --user adafruit-nrfutil
  - umake electronics arduino
  #- arduino --install-library "Adafruit GFX","Adafruit NeoPixel","Adafruit DotStar","Adafruit SSD1306"

script:
  - arduino --version
   #- build_nrf5x_platforms
